services:
  pim_connector.flat_translators.product_translator:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\ProductAndProductModelFlatTranslator
    arguments:
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
      - '@pim_connector.array_converter.flat_to_standard.product.association_columns_resolver'
      - '@akeneo.pim.structure.query.get_attribute_translations'
      - '@pim_catalog.localization.translator.label'
      - '@akeneo.pim.structure.query.get_association_type_translations'
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_column_info_extractor'
      - '@pim_connector.flat_translators.property_value_translator_registry'
      - '@pim_connector.flat_translators.attribute_value_translator_registry'
      - '@pim_connector.flat_translators.header_translator_registry'

  pim_connector.flat_translators.product_model_translator:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\ProductAndProductModelFlatTranslator
    arguments:
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
      - '@pim_connector.array_converter.flat_to_standard.product.association_columns_resolver'
      - '@akeneo.pim.structure.query.get_attribute_translations'
      - '@pim_catalog.localization.translator.label'
      - '@akeneo.pim.structure.query.get_association_type_translations'
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_column_info_extractor'
      - '@pim_connector.flat_translators.property_value_translator_registry'
      - '@pim_connector.flat_translators.attribute_value_translator_registry'
      - '@pim_connector.flat_translators.header_translator_registry'

  ## Registries
  pim_connector.flat_translators.header_translator_registry:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatHeaderTranslatorRegistry

  pim_connector.flat_translators.property_value_translator_registry:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatPropertyValueTranslatorRegistry

  pim_connector.flat_translators.attribute_value_translator_registry:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatAttributeValueTranslatorRegistry
    arguments:
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_column_info_extractor'

  ## Property translators
  pim_connector.flat_translators.property_value_translator.category:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatPropertyValueTranslator\CategoryFlatTranslator
    arguments:
      - '@akeneo.pim.structure.query.get_category_translations'
    tags: [{ name: pim_connector.flat_translators.property_value_translator }]

  pim_connector.flat_translators.property_value_translator.family:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatPropertyValueTranslator\FamilyFlatTranslator
    arguments:
      - '@akeneo.pim.structure.query.get_family_translations'
    tags: [{ name: pim_connector.flat_translators.property_value_translator }]

  pim_connector.flat_translators.property_value_translator.group:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatPropertyValueTranslator\GroupFlatTranslator
    arguments:
      - '@akeneo.pim.structure.query.get_group_translations'
    tags: [{ name: pim_connector.flat_translators.property_value_translator }]

  pim_connector.flat_translators.property_value_translator.enabled:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatPropertyValueTranslator\EnabledFlatTranslator
    arguments:
      - '@pim_catalog.localization.translator.label'
    tags: [{ name: pim_connector.flat_translators.property_value_translator }]

  pim_connector.flat_translators.property_value_translator.parent:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatPropertyValueTranslator\ParentFlatTranslator
    arguments:
      - '@akeneo.pim.enrichment.product.query.get_product_model_label'
    tags: [{ name: pim_connector.flat_translators.property_value_translator }]

  ## Attribute translators
  pim_connector.flat_translators.attribute_value_translator.boolean:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatAttributeValueTranslator\BooleanFlatTranslator
    arguments:
      - '@pim_catalog.localization.translator.label'
    tags: [{ name: pim_connector.flat_translators.attribute_value_translator }]

  pim_connector.flat_translators.attribute_value_translator.metric_unit:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatAttributeValueTranslator\MetricUnitFlatTranslator
    tags: [{ name: pim_connector.flat_translators.attribute_value_translator }]

  pim_connector.flat_translators.attribute_value_translator.multi_select:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatAttributeValueTranslator\MultiSelectFlatTranslator
    arguments:
      - '@akeneo.pim.structure.query.lru_cached_get_existing_attribute_options_with_values'
    tags: [{ name: pim_connector.flat_translators.attribute_value_translator }]

  pim_connector.flat_translators.attribute_value_translator.simple_select:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatAttributeValueTranslator\SimpleSelectFlatTranslator
    arguments:
      - '@akeneo.pim.structure.query.lru_cached_get_existing_attribute_options_with_values'
    tags: [{ name: pim_connector.flat_translators.attribute_value_translator }]

  ## Header translators
  pim_connector.flat_translators.header_translator.association_identifier:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatHeaderTranslator\AssociationIdentifierFlatHeaderTranslator
    arguments:
      - '@pim_connector.array_converter.flat_to_standard.product.association_columns_resolver'
      - '@pim_catalog.localization.translator.label'
    tags: [{ name: pim_connector.flat_translators.header_translator }]

  pim_connector.flat_translators.header_translator.association_quantity:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatHeaderTranslator\AssociationQuantityFlatHeaderTranslator
    arguments:
      - '@pim_connector.array_converter.flat_to_standard.product.association_columns_resolver'
      - '@pim_catalog.localization.translator.label'
    tags: [{ name: pim_connector.flat_translators.header_translator }]

  pim_connector.flat_translators.header_translator.attribute:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatHeaderTranslator\AttributeFlatHeaderTranslator
    arguments:
      - '@pim_catalog.localization.translator.label'
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_column_info_extractor'
    tags: [{ name: pim_connector.flat_translators.header_translator }]

  pim_connector.flat_translators.header_translator.property:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\FlatHeaderTranslator\PropertyFlatHeaderTranslator
    arguments:
      - '@pim_catalog.localization.translator.label'
    tags: [{ name: pim_connector.flat_translators.header_translator }]
