services:
  pim_connector.flat_translators.product_translator:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\ProductFlatTranslator
    arguments:
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
      - '@pim_connector.array_converter.flat_to_standard.product.association_columns_resolver'
      - '@akeneo.pim.structure.query.get_attribute_translations'
      - '@pim_catalog.localization.translator.label'
      - '@akeneo.pim.structure.query.get_association_type_translations'
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_column_info_extractor'
      - '@pim_connector.flat_translators.property_translator_registry'
      - '@pim_connector.flat_translators.attribute_translator_registry'
      - '@pim_connector.flat_translators.header_translator_registry'

  pim_connector.flat_translators.product_model_translator:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\NullFlatTranslator

  pim_connector.flat_translators.published_product_translator:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\NullFlatTranslator

  ## Registries
  pim_connector.flat_translators.header_translator_registry:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\HeaderFlatTranslatorRegistry

  pim_connector.flat_translators.property_translator_registry:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\PropertyTranslatorRegistry

  pim_connector.flat_translators.attribute_translator_registry:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\AttributeTranslatorRegistry
    arguments:
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_column_info_extractor'

  ## Property translators
  pim_connector.flat_translators.property_translator.category:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\PropertyTranslator\CategoryFlatTranslator
    arguments:
      - '@akeneo.pim.structure.query.get_category_translations'
    tags: [{ name: pim_connector.flat_translators.property_translator }]

  pim_connector.flat_translators.property_translator.family:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\PropertyTranslator\FamilyFlatTranslator
    arguments:
      - '@akeneo.pim.structure.query.get_family_translations'
    tags: [{ name: pim_connector.flat_translators.property_translator }]

  pim_connector.flat_translators.property_translator.group:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\PropertyTranslator\GroupFlatTranslator
    arguments:
      - '@akeneo.pim.structure.query.get_group_translations'
    tags: [{ name: pim_connector.flat_translators.property_translator }]

  pim_connector.flat_translators.property_translator.enabled:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\PropertyTranslator\EnabledFlatTranslator
    arguments:
      - '@pim_catalog.localization.translator.label'
    tags: [{ name: pim_connector.flat_translators.property_translator }]

  pim_connector.flat_translators.attribute_translator.parent:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\PropertyTranslator\ParentFlatTranslator
    arguments:
      - '@akeneo.pim.enrichment.product.query.get_product_model_label'
    tags: [{ name: pim_connector.flat_translators.property_translator }]

  ## Attribute translators
  pim_connector.flat_translators.attribute_translator.boolean:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\AttributeTranslator\BooleanFlatTranslator
    arguments:
      - '@pim_catalog.localization.translator.label'
    tags: [{ name: pim_connector.flat_translators.attribute_translator }]

  pim_connector.flat_translators.attribute_translator.metric_unit:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\AttributeTranslator\MetricUnitFlatTranslator
    tags: [{ name: pim_connector.flat_translators.attribute_translator }]

  pim_connector.flat_translators.attribute_translator.multi_select:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\AttributeTranslator\MultiSelectFlatTranslator
    arguments:
      - '@akeneo.pim.structure.query.lru_cached_get_existing_attribute_options_with_values'
    tags: [{ name: pim_connector.flat_translators.attribute_translator }]

  pim_connector.flat_translators.attribute_translator.simple_select:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\AttributeTranslator\SimpleSelectFlatTranslator
    arguments:
      - '@akeneo.pim.structure.query.lru_cached_get_existing_attribute_options_with_values'
    tags: [{ name: pim_connector.flat_translators.attribute_translator }]

  ## Header translators
  pim_connector.flat_translators.header_translator.association_identifier:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\HeaderFlatTranslator\AssociationIdentifierHeaderFlatTranslator
    arguments:
      - '@pim_connector.array_converter.flat_to_standard.product.association_columns_resolver'
      - '@pim_catalog.localization.translator.label'
    tags: [{ name: pim_connector.flat_translators.header_translator }]

  pim_connector.flat_translators.header_translator.association_quantity:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\HeaderFlatTranslator\AssociationQuantityHeaderFlatTranslator
    arguments:
      - '@pim_connector.array_converter.flat_to_standard.product.association_columns_resolver'
      - '@pim_catalog.localization.translator.label'
    tags: [{ name: pim_connector.flat_translators.header_translator }]

  pim_connector.flat_translators.header_translator.attribute:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\HeaderFlatTranslator\AttributeHeaderFlatTranslator
    arguments:
      - '@pim_catalog.localization.translator.label'
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_column_info_extractor'
    tags: [{ name: pim_connector.flat_translators.header_translator }]

  pim_connector.flat_translators.header_translator.property:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\HeaderFlatTranslator\PropertyHeaderFlatTranslator
    arguments:
      - '@pim_catalog.localization.translator.label'
    tags: [{ name: pim_connector.flat_translators.header_translator }]
