services:
  pim_connector.flat_translators.product_translator:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\ProductFlatTranslator
    arguments:
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
      - '@pim_connector.array_converter.flat_to_standard.product.association_columns_resolver'
      - '@akeneo.pim.structure.query.get_attribute_translations'
      - '@pim_catalog.localization.translator.label'
      - '@akeneo.pim.structure.query.get_association_type_translations'
      - '@akeneo.pim.structure.query.get_category_translations'
      - '@akeneo.pim.structure.query.get_family_translations'
      - '@akeneo.pim.structure.query.get_group_translations'
      - '@pim_connector.array_converter.flat_to_standard.product.attribute_column_info_extractor'

  pim_connector.flat_translators.product_model_translator:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\NullFlatTranslator

  pim_connector.flat_translators.published_product_translator:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\FlatTranslator\NullFlatTranslator
