parameters:
    pim_catalog.localization.translator.proxy.class: Akeneo\Tool\Component\Localization\TranslatorProxy

services:
    pim_catalog.localization.translator.proxy:
        class: '%pim_catalog.localization.translator.proxy.class%'
        arguments:
            - '@translator'

    pim_catalog.localization.translator.label:
        class: 'Akeneo\Tool\Component\Localization\LabelTranslator'
        arguments:
            - '@translator.data_collector.inner'
